name: Docs

on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
  workflow_dispatch:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  
  docs:
    name: ${{ matrix.pkg.shortcut }}
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skipci') }}
    permissions:
      contents: write
      statuses: write
    strategy:
      fail-fast: false
      matrix:
        pkg:
          - name: DifferentiationInterface
            shortcut: DI
            dir: './DifferentiationInterface'
          - name: DifferentiationInterfaceTest
            shortcut: DIT
            dir: './DifferentiationInterfaceTest'
    
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'  # TODO: 1
      - uses: julia-actions/cache@v1
      - name: Install dependencies
        run: julia --project=${{ matrix.pkg.dir}}/docs/ -e '
          using Pkg;
          Pkg.Registry.update();
          if "${{ matrix.pkg.name}}" == "DifferentiationInterface";
              Pkg.develop(PackageSpec(path="./DifferentiationInterface"));
          else;
              Pkg.develop([PackageSpec(path="./DifferentiationInterface"), PackageSpec(path="${{ matrix.pkg.dir}}")]);
          end;
          Pkg.instantiate();'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
        run: julia --project=${{ matrix.pkg.dir}}/docs/ ${{ matrix.pkg.dir}}/docs/make.jl